name: Deploy to GitHub Pages
on:
  push:	
    branches:	
      - ops-grillage

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/source"
  #  - name: Build and Commit
  #    uses: sphinx-notes/pages@master
  #    with:
  #      target_branch: gh-pages-test
  #      repository_path: .
  #      documentation_path: docs/source
  #      install_requirements: true
        
#     - name: Deploy
#       uses: s0/git-publish-subdir-action@develop
#       env:
#         REPO: self
#         BRANCH: gh-pages
#         FOLDER: docs/build/html
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
